# Generated by Django 5.2.12 on 2026-09-27 15:26

import django.core.validators
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_backfill_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='ข้อมูลไบต์ PDF'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=research.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), research.models.validate_file_size], verbose_name='ไฟล์ PDF ฉบับเต็ม'),
        ),
    ]
